### ISSUE TITLE
compatibility with django 3 (django.utils.six has been removed)

### ISSUE THREAD

**Issue by moyid** [danielquinn/django-encrypted-filefield#15]
Hi! I really like this library, but it is now causing an import error because it uses django.utils.six, which has been removed from django 3. I'm creating this issue to request for compatibility with Django 3. Thank you!

**Comment by gurugeek** [comment]
same issue for me, I would be grateful for an upgrade to Django 3

**Comment by danielquinn** [comment]
Thanks to @odelseth, this has now been fixed in `0.2.2`.  Sorry for taking so long!  Have a look at my comments on #14 regarding what's coming down the pipe for this library around support for older versions of Python & Django.
