### ISSUE TITLE
template error

### ISSUE THREAD

**Issue by cat-owl** [danielquinn/django-encrypted-filefield#6]
i have this error :

> type object 'FieldFile' has no attribute '_get_url'

when i want to display an encrypted image in my template

this is my template code :
`<img style="width: 150px;" src="{{ obj.image.url }}" alt=""/>`

**Comment by danielquinn** [comment]
Hi @semilanceata this should now be fixed in `master`.  Thanks to #5.  I'll update PyPi shortly.
