### ISSUE TITLE
Error using django.core.urlresolvers

### ISSUE THREAD

**Issue by spaceriqui** [danielquinn/django-encrypted-filefield#7]
Hi.

Fairly new at this, so this may be user error.   On Django 2.0, the `django.core.urlresolvers` module is removed in favor of its new location, `django.urls`.

https://docs.djangoproject.com/en/2.0/releases/2.0/

It appears `django-encrypted-filefield` is using `django.core.urlresolvers` in three places:

demo/views.py
django_encrypted_filefiled/checks.py and fields.py

Seems to work fine when replaced.

Using Django 2.0.1 and django_encrypted_filefield 0.1.3 on python 3.4.3

**Comment by danielquinn** [comment]
Ooh, yes thanks for noting this.  I'm happy to accept a pull-request (that works for 1.11 as well) if you'd like to contribute, otherwise, I'll try to see to this when I've got some time.

**Comment by spaceriqui** [comment]
Thank you for the reply.  Created pull request #9.

**Comment by danielquinn** [comment]
Fixed in #9!
